language: php

php:
  - 7.3
  - 7.4

os: linux

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

after_success:
 - set -e
 - sudo apt-get install -y lftp
 - lftp -c "set ftps:initial-prot ''; set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate false; open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:21; mirror -eRv -x ^\. -x node_modules/ $FTP_DIR .; quit;"

script:
  - vendor/bin/phpunit
