language: php

php:
  - 7.4

os: linux

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key:generate

after_success:
 - set -e
 - sudo apt-get install -y lftp
 - lftp -c "open ftp://$FTP_USER:$FTP_PASS@$FTP_HOST:21; mirror -eRv -x node_modules/ $FTP_DIR .; quit;"

script:
  - vendor/bin/phpunit
